### ISSUE TITLE
Docbook redirection error

### ISSUE THREAD

**Issue by vesnikos** [eerohele/markup-schemas#1]
Hi,

I was building the project with ant and i got this error:
>docbook:
>    [get] Getting: http://www.docbook.org/xml/5.0/docbook-5.0.zip
>      [get] To: /tmp/docbook-5.0.zip
>      [get] http://www.docbook.org/xml/5.0/docbook-5.0.zip permanently moved to https://docbook.org/xml/5.0/docbook-5.0.zip
>
>BUILD FAILED
>/catalogs/build.xml:118: The following error occurred while executing this line:
>/catalogs/build.xml:32: Redirection detected from http to https. Protocol switch unsafe, not allowed.

**Comment by eerohele** [comment]
Thanks for reporting!

Can you try changing the URL protocols in the [`build.xml` file](https://github.com/eerohele/catalogs/blob/337ca7bd3e257fd59e6877e0581692107309fdbb/build.xml#L116-L122) in your clone of the repository to `https` and see whether that fixes the issue?

**Comment by vesnikos** [comment]
it works ok after you point to the right URL. docbook 4.5 has moved too:

5.0 : https://docbook.org/xml/5.0/docbook-5.0.zip
4.5 : https://docbook.org/xml/4.5/docbook-xml-4.5.zip

**Comment by eerohele** [comment]
Thanks! Fixed in c1edd4d8b08ebdfc6f645a54876eecd2f857f845.
